### ISSUE TITLE
Build not honoring ENABLE_PYTHON=OFF

### ISSUE THREAD

**Issue by boogachamp** [sandialabs/gr-fhss_utils#2]
When disabling Python/Swig gnuradio support the build fails.

Used cmake -DENABLE_PYTHON:BOOL=OFF flag to set

Fixed locally by wrapping the addition of subdirectories:

if (ENABLE_PYTHON)
  add_subdirectory(swig)
  add_subdirectory(python)
endif(ENABLE_PYTHON)

**Comment by jacobgilbert-snl** [comment]
Fixed with 42c8527069c14c1bd971f5c722cec116f6e4b694
