### ISSUE TITLE
Missing blocks in fhss_detector_reference.grc

### ISSUE THREAD

**Issue by BitBangingBytes** [sandialabs/gr-fhss_utils#7]
When loading the fhss_detector_reference.grc flowgraph from the examples directory of the maint-3.8 branch, two blocks show as missing. fhss_utils_fine_burst_measure is shown in one, and fhss_utils_pdu_quadrature_demod_cf is shown in the other.

**Comment by jacobgilbert-snl** [comment]
This should be fixed with 0ddb26faff08646c525ccd5da833dec75911b2c3
